### ISSUE TITLE
Error: Fractal themes must inherit from the base Theme class.

### ISSUE THREAD

**Issue by jamesmacwhite** [frctl/fractal#1039]
### Steps to reproduce the issue

Following the guidance to modify the hex values of the default skin, I have the following in my fractal.config.js file:

```js
const fractal = require('@frctl/fractal').create();
const mandelbrot = require('@frctl/mandelbrot');

const customTheme = mandelbrot({
    skin: {
        name: 'default',
        accent: '#092644',
        complement: '#ffffff',
        links: '#12B9A5',
    },
    format: 'yaml',
    lang: 'en-GB'
});

fractal.web.theme(customTheme);

module.exports = fractal;
```

This works when starting the dev server but fails with fractal builder for exporting the styleguide as HTML.

This throws the following exception:

```
Unhandled rejection Error: Fractal themes must inherit from the base Theme class.
    at Web._loadTheme (/home/jameswhite/Projects/college-website/node_modules/@frctl/web/src/web.js:76:19)
    at Web.builder (/home/jameswhite/Projects/college-website/node_modules/@frctl/web/src/web.js:37:28)
    at CommandInstance.action (/home/jameswhite/Projects/college-website/node_modules/@frctl/fractal/src/cli/commands/web.build.js:12:42)
    at CommandInstance.<anonymous> (/home/jameswhite/Projects/college-website/node_modules/@frctl/fractal/src/cli/cli.js:92:37)
    at Session.session.execCommandSet (/home/jameswhite/Projects/college-website/node_modules/vorpal/dist/session.js:470:20)
    at Vorpal.vorpal._exec (/home/jameswhite/Projects/college-website/node_modules/vorpal/dist/vorpal.js:960:18)
    at Vorpal.vorpal._execQueueItem (/home/jameswhite/Projects/college-website/node_modules/vorpal/dist/vorpal.js:751:17)
    at Vorpal.vorpal._queueHandler (/home/jameswhite/Projects/college-website/node_modules/vorpal/dist/vorpal.js:735:10)
    at Vorpal.vorpal.exec (/home/jameswhite/Projects/college-website/node_modules/vorpal/dist/vorpal.js:682:10)
    at Vorpal.parse (/home/jameswhite/Projects/college-website/node_modules/vorpal/dist/vorpal.js:166:12)
    at app.load.then (/home/jameswhite/Projects/college-website/node_modules/@frctl/fractal/src/cli/cli.js:198:24)
    at tryCatcher (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/promise.js:643:18)
    at PromiseArray._resolve (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/jameswhite/Projects/college-website/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
```

I could only find this issue that was similar: https://github.com/frctl/fractal/issues/821. However in my case I am not creating an entire subtheme just modifying values on the default skin.

Any ideas what I'm doing wrong?

### Context

-   Fractal version: 1.5.2
-   Node version: v10.19.0
-   OS: WSL2 (Ubuntu)

**Comment by jamesmacwhite** [comment]
It appears it is not related to the task file as commenting it all out still throws the error, it would appear it is related to the web theme setting, with the customisations.

**Comment by jamesmacwhite** [comment]
Bumping my Fractal dependency to 1.5.6 seems to fix this.

**Comment by mihkeleidast** [comment]
FYI I released a fix that should alleviate this problem further, see #969.

**Comment by jamesmacwhite** [comment]
@mihkeleidast Thank you! I managed to find the issue because this project has two branches, one branch was fine and the other was throwing the error with the custom theme I then tracked down the fact the Fractal dependency between them was different. I'm guessing by updating to the latest version it has incorporated that fix to allow custom themes to work correctly as per the guide.

**Comment by mihkeleidast** [comment]
I got the release published a minute ago - it failed in the morning. But I think you managed to fix your issue by just aligning the versions, which works as well :)

**Comment by jamesmacwhite** [comment]
Nice. Thank you!
