### ISSUE TITLE
Doing a static build has some issues

### ISSUE THREAD

**Issue by custa1200** [frctl/fractal#163]
Hey @allmarkedup,
Just tried to do a static build and get the following in the console:

```
✔ Build started...
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (/Users/mjohnston/projects/styleglide2/node_modules/handlebars-helpers/node_modules/helper-date/node_modules/moment/moment.js:285:105)
    at configFromString (/Users/mjohnston/projects/styleglide2/node_modules/handlebars-helpers/node_modules/helper-date/node_modules/moment/moment.js:2015:32)
    at configFromInput (/Users/mjohnston/projects/styleglide2/node_modules/handlebars-helpers/node_modules/helper-date/node_modules/moment/moment.js:2375:13)
    at prepareConfig (/Users/mjohnston/projects/styleglide2/node_modules/handlebars-helpers/node_modules/helper-date/node_modules/moment/moment.js:2358:13)
    at createFromConfig (/Users/mjohnston/projects/styleglide2/node_modules/handlebars-helpers/node_modules/helper-date/node_modules/moment/moment.js:2325:44)
    at createLocalOrUTC (/Users/mjohnston/projects/styleglide2/node_modules/handlebars-helpers/node_modules/helper-date/node_modules/moment/moment.js:2412:16)
    at local__createLocal (/Users/mjohnston/projects/styleglide2/node_modules/handlebars-helpers/node_modules/helper-date/node_modules/moment/moment.js:2416:16)
    at utils_hooks__hooks (/Users/mjohnston/projects/styleglide2/node_modules/handlebars-helpers/node_modules/helper-date/node_modules/moment/moment.js:16:29)
    at Object.momentHelper (/Users/mjohnston/projects/styleglide2/node_modules/handlebars-helpers/node_modules/helper-date/index.js:42:15)
    at Object.helperWrapper (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/handlebars/node_modules/promised-handlebars/index.js:130:23)
    at Object.<anonymous> (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/handlebars/node_modules/promised-handlebars/lib/utils.js:29:28)
    at Object.eval (eval at createFunctionContext (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:8:70)
    at main (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at prepareAndResolveMarkers (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/handlebars/node_modules/promised-handlebars/index.js:99:39)
    at /Users/mjohnston/projects/styleglide2/node_modules/@frctl/handlebars/node_modules/promised-handlebars/lib/utils.js:29:28
    at HandlebarsAdapter.render (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/handlebars/src/adapter.js:30:30)
    at ComponentSource._renderVariant (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/fractal/src/api/components/source.js:207:30)
    at next (native)
    at onFulfilled (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/fractal/node_modules/co/index.js:65:19)
    at tryCatcher (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/fractal/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/fractal/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/fractal/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/fractal/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/fractal/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/fractal/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Users/mjohnston/projects/styleglide2/node_modules/@frctl/fractal/node_modules/bluebird/js/release/promise.js:431:57)
⚑ Exported 760 of 992 items
✔ Build finished with no errors.
```

**Comment by allmarkedup** [comment]
Hey @custa1200 that looks like an issue (or rather a deprecation notice) in the handlebars-helpers library - but not one that should actually affect the output of the build. Is the generated site still as you would expect or does it have problems?

**Comment by dkhuntrods** [comment]
Hi @custa1200 I'm going to close this since we haven't heard any more from you about this, but if it's still ongoing do let me know and I can re-open.
