### ISSUE TITLE
"@[handle]" convention collides with Handlebars' special "@partial-block"

### ISSUE THREAD

**Issue by nategreen** [frctl/fractal#221]
From [Handlebars' docs](http://handlebarsjs.com/partials.html#partial-block):

> [Block] syntax may also be used to pass templates to the partial, which can be executed by the specially named partial, @partial-block.

It seems that inside of Fractal, that doesn't work...I'm assuming that's because Fractal's sucking up any partials with a name prefixed by `@`.

This isn't a show-stopper—you can accomplish the same thing with "inline partials"—but I figure it should at least be documented, especially since the `@[handles]` stuff can't be turned off (as the rest of the handlebars helpers can).

**Comment by dkhuntrods** [comment]
@nategreen I've successfully used `@partial-block` within Fractal, but there's a small caveat. I wrote about it here: https://clearleft.com/posts/417 - see Container Components.

**Comment by nategreen** [comment]
@dkhuntrods Thanks!

**Comment by dkhuntrods** [comment]
Cool, does this resolve your issue @nategreen? If so, mind if I close this issue?

**Comment by nategreen** [comment]
Yeah, go ahead and close it. If someone else runs into this, at least it's documented here. :+1:

**Comment by dkhuntrods** [comment]
Great, thanks. It's more a handlebars thing than a fractal thing, but probably worth us mentioning in an examples section.

**Comment by nategreen** [comment]
So, I was using your `{{#if }}` trick but all of a sudden components that used partial blocks are throwing an error:

```
ERROR RENDERING COMPONENT
Cannot set property '_self' of undefined
 TypeError: Cannot set property '_self' of undefined
    at Object.hbs.VM.invokePartial (C:\dev\mri-ux\node_modules\@frctl\handlebars\src\adapter.js:69:45)
    at Object.invokePartialWrapper [as invokePartial] (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\runtime.js:68:39)
    at eval (eval at createFunctionContext (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), :8:28)
    at prog (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\runtime.js:221:12)
    at Object.partialBlockWrapper (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\runtime.js:268:16)
    at Object. (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:10:33)
    at Object.helperWrapper (C:\dev\mri-ux\node_modules\promised-handlebars\index.js:130:23)
    at Object. (C:\dev\mri-ux\node_modules\promised-handlebars\lib\utils.js:29:28)
    at Object.eval [as main] (eval at createFunctionContext (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), :8:32)
    at main (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\runtime.js:175:32)
    at ret (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\runtime.js:178:12)
    at ret (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at prepareAndResolveMarkers (C:\dev\mri-ux\node_modules\promised-handlebars\index.js:92:17)
    at C:\dev\mri-ux\node_modules\promised-handlebars\lib\utils.js:29:28
    at Object.invokePartial (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\runtime.js:283:12)
    at Object.hbs.VM.invokePartial (C:\dev\mri-ux\node_modules\@frctl\handlebars\src\adapter.js:73:38)
    at Object.hbs.VM.invokePartial (C:\dev\mri-ux\node_modules\@frctl\handlebars\src\adapter.js:73:38)
    at Object.invokePartialWrapper [as invokePartial] (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\runtime.js:68:39)
    at Object.eval [as main] (eval at createFunctionContext (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), :5:31)
    at main (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\runtime.js:175:32)
    at ret (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\runtime.js:178:12)
    at ret (C:\dev\mri-ux\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
```

Here's my container partial:

```html
<div class="overlay {{ classes }}">
    {{#if @partial-block}}
        {{> @partial-block }}
    {{/if}}
</div>
```

And the partial that calls it:

```
{{#> @overlay classes="drawer__overlay"}}
  <div class="drawer">
    
  ... contents of the drawer ...

  </div>
{{/ @overlay }}
```

Any ideas?

**Comment by nategreen** [comment]
Wait, what the heck...I took *out* the `{{#if }}` and now it's working. :confounded:

**Comment by dkhuntrods** [comment]
@nategreen So if you just use `{{>@partial-block }}` without the if-block, all is well? 
I'd just started getting that message on a fresh install of an older project, but hadn't had time to check it out. I'm thinking it's a subtle internal change in handlebars that's making the adapter fail in certain edge cases.

**Comment by nategreen** [comment]
Right, exactly. The new container partial:

```
<div class="overlay {{ classes }}">
    {{> @partial-block }}
</div>
```

Very odd.

**Comment by nategreen** [comment]
Narrowed it down somewhat. Here's the state of my problem as of right now:

- If I include the `{{#if}}` trick, and include just HTML and Handlebars interpolation inside of that component, everything works.
- If I include the `{{#if}}` trick, and try to call another partial from inside of that component, it fails. (`TypeError: Cannot set property '_self' of undefined`)
- If I _exclude_ the `{{#if}}` trick, I can do whatever I want inside that component, but the component _itself_ fails to render in Fractal. (`Error: The partial @partial-block could not be found`)

Very strange.

**Comment by dkhuntrods** [comment]
Hi @nategreen, this error seems to be due to a change in how handlebars handles `@partial-block`s, which now makes the `if` trick unnecessary.
I've corrected the error in my own templates using the block syntax which they describe in their docs - along the lines of 
```
{{#>@partial-block}}
fallback content
{{/@partial-block}}
```

**Comment by fvanderwielen** [comment]
Leaving the link to the previously mentioned blogpost here, as the URL has changed over the years: https://clearleft.com/posts/to-which-are-added-some-notes-upon-using-fractal-for-the-first-time
