### ISSUE TITLE
Error with render helper (in inline partial?)

### ISSUE THREAD

**Issue by nategreen** [frctl/fractal#305]
I don't know exactly how to reproduce this, but here's what I'm running into. Basically, I'm trying to use Handlebars [inline partials](http://handlebarsjs.com/partials.html#inline-partials) to make an accordion that I can "build" elsewhere. When I try to use the `{{render "..." }}` partial inside that inline partial (I *think* that's what causing it anyway), it breaks.

My component (note the line I've called out with a button `render`ed):

```html
 {{#*inline "section" }}
    <section class="accordion__section{{#if this.closed }} is-closed{{/if }}">
      <header tabindex="0" class="accordion__section-header">
        <h1 class="accordion__section-heading">{{ this.heading }}</h1>
        <span class="caret accordion__section-caret"></span>
      </header>
       <div class="accordion__section-body">
          {{#if @partial-block }}
            {{> @partial-block }}
          {{else }}
            <span></span>
          {{/if }}
      </div>
    </section>
{{/inline }} 

<div class="accordion {{ classes }}">
  {{#if @partial-block }}
    {{> @partial-block }}
  {{else }}
    {{#> section heading="Section 1" }}
      {{render "@button"}} {!-- the offending line --}
    {{/section }}
    {{#> section heading="Section 2" }}

    {{/section }}
    {{#> section heading="Section 3" }}

    {{/section }}
  {{/if }}
</div>
```

Rendering error:

```
ERROR RENDERING COMPONENT
Cannot read property '_env' of undefined
 TypeError: Cannot read property '_env' of undefined
    at source.resolve.then.context (C:\dev\mri-ux\node_modules\@frctl\handlebars\src\helpers\render.js:35:53)
    at tryCatcher (C:\dev\mri-ux\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\dev\mri-ux\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\dev\mri-ux\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\dev\mri-ux\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\dev\mri-ux\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\dev\mri-ux\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\dev\mri-ux\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\dev\mri-ux\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by dkhuntrods** [comment]
Hi @nategreen, I can't find the thread but I know there was an update to handlebars some time ago that made the 
```
{{#if @partial-block }}
  {{> @partial-block }}
{{else }}
```
syntax invalid.

It needs to be 
```
{{#>@partial-block}}
  fallback-stff
{{/@partial-block }}
```

If you give that a try, does it help?

**Comment by nategreen** [comment]
Ah, yes. It does. Apparently inline partials don't work the way I thought they did, but all seems to be working as expected now. :) Thanks!
