### ISSUE TITLE
Invalid Regular Expression Error

### ISSUE THREAD

**Issue by garethf89** [frctl/fractal#526]
C:\XXX\Website\ComponentLibrary\node_modules\@frctl\fractal\src\web\server.js:160
                const pathMatch = new RegExp(`^${s.path}`);
                                 ^

SyntaxError: Invalid regular expression: /^C:\XXX\Website\ComponentLibrary\assets\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at getFilePaths (C:\XXX\Website\ComponentLibrary\node_modules\@frctl\fractal\src\web\server.js:160:35)
    at FSWatcher.<anonymous> (C:\XXX\Website\ComponentLibrary\node_modules\@frctl\fractal\src\web\server.js:163:63)
    at FSWatcher.emit (events.js:210:5)
    at FSWatcher.<anonymous> (C:\XXX\Website\ComponentLibrary\node_modules\@frctl\fractal\node_modules\chokidar\index.js:196:15)
    at FSWatcher._emit (C:\XXX\Website\ComponentLibrary\node_modules\@frctl\fractal\node_modules\chokidar\index.js:238:5)
    at FSWatcher.<anonymous> (C:\XXX\Website\ComponentLibrary\node_modules\@frctl\fractal\node_modules\chokidar\lib\nodefs-handler.js:263:16)
    at FSReqCallback.oncomplete (fs.js:159:5)

### Description

The error shown above when I run fractal start --sync on a Windows machine and click on anything.

### Steps to Reproduce

I get this error by running fractal start --sync, then clicking on any section in the browser. Sometimes I am able to click on a few before it breaks.

**Reproduces how often:** 

Either first click or after many

### Versions

1.2.0

**Comment by Chapabu** [comment]
I'm afraid I don't have easy access to a Windows machine. Tagged as help-wanted in case someone else can have a stab at this one.

**Comment by sebimoe** [comment]
Just to report, I get that error:

    ...node_modules\@frctl\fractal\src\web\server.js:160
                const pathMatch = new RegExp(`^${s.path}`);
    SyntaxError: Invalid regular expression: /^C:\projects\...\/: \ at end of pattern

It appears path is not regex-escaped, here is a stackoverflow answer for converting a string to a regex matching it: https://stackoverflow.com/a/6969486/639370

It should be sufficient to use `${escapeRegExp(s.path)}` here and in similar regex usages. Hope it helps.

**Comment by sebimoe** [comment]
Actually looks like that line is not needed
