### ISSUE TITLE
Fractal new fails after trying to install NPM dependencies

### ISSUE THREAD

**Issue by Johnnybar** [frctl/fractal#550]
Have you read Fractal's [Code of Conduct](/.github/CODE_OF_CONDUCT.md)? By filing an Issue, you are expected to comply with it, including treating everyone with respect

Do you want to ask a question? Are you looking for support? The Fractal Discord server is the best place for getting support:
https://discord.gg/vuRz4Yx

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Fractal Documentation for information about your issue: https://fractal.build/guide
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Afrctl

### Description

I've had no issues installing fractal projects in the past, but `fractal new [projectname]` seems to crash after beginning to install NPM dependencies.

Thanks for your help

### Steps to Reproduce

1. Install most recent version of fractal globally with `npm i -g @frctl/fractal`
2. Create folder for project
3. CD into project directory and un `fractal new test-project`

**Expected behavior:** A new fractal project is created with boilerplate structure

**Actual behavior:** Installation begins and fails in this way:
```
? Will you use Git for version control on this project? Yes
Generating project structure...
Installing NPM dependencies - this may take some time!
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Reproduces how often:** 100%

### Versions

* What version of Fractal are you running? (run `npm list @frctl/fractal` / `yarn list @frctl/fractal`
this is the response when running `npm list...`:
`-- (empty)`
however, when I run fractal -v, I get the following response: ```
│ Fractal CLI                                                  │
│──────────────────────────────────────────────────────────────│
│ No local Fractal configuration found.                        │
│ You can use the fractal new command to create a new project. │
│──────────────────────────────────────────────────────────────│
│ Powered by Fractal v1.2.1          
```
* What version of Node.js are you running? (run `node -v`)
v10.16.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Johnnybar** [comment]
Everything is working after running `npm i` after the installation fails. So, this is only an issue with the startup command.
